# local profile
spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hanziboong
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    path: /v3/api-docs  # 기본 스펙 JSON 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 접속 경로
    operationsSorter: alpha  # API 목록 알파벳 순 정렬
    tagsSorter: alpha        # 태그 알파벳 순 정렬
    display-request-duration: true  # 요청/응답 시간 표시
    syntax-highlight:
      theme: nord            # 코드 하이라이트 테마
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
